project:
  type: website
  output-dir: docs
  resources:
    - CNAME

website:
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: aboutme.qmd
      - text: "Science"
        menu:
          - text: "Current Research"
            href: research.qmd
          - text: "Publications & Presentations"
            href: publications.qmd      
      - text: "For Parents"
        menu: 
          - text: "From screens to living room"
            href: parents.qmd
          - text: "Resources & Media"
            href: external-resources.qmd
      - text: "Original Animation"
        href: media.qmd
      - text: "CV"
        href: https://docs.google.com/document/d/1f0oJF5Z-9KS5E2RWP6F0K8944ZjfMALe/export?format=pdf
        target: _blank
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/henrique-santos-/
      - icon: envelope
        href: mailto:hepereir@ucsc.edu

format:
  html:
    theme:
      light: [cosmo, custom.scss]
    toc: false
    mainfont: "Inter, sans-serif"

editor: visual